[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

## /target is excluded from being pushed so upon cloning and 
## running anchor build and then anchor deploy
## newly created program addresses have to be pasted below
## as well as into respective programs and then need to run 
## anchor build and then anchor deploy
## AGAIN

[programs.localnet]
example_lottery = "HeF9ezjTNNgjw3QYrsVkTXvBSyzMn4wFZyDppe7wUsJW" 
example_rps = "4DC2PDZrgD44bsi9zKRpxsX4nYzS5pxJAMCr7XbseMLv"
example_consortium = "536gqYtnehQGUmoNs1vx9JfUDAkZi2fZwGQTgoJw98Rp"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_lottery.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_rps.ts"
test3 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_consortium.ts"

